# Generated by Django 5.0.1 on 2024-06-29 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0016_confirmbooking_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='dateslot',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
